@Backend_HostAddress = https://localhost:5004

GET {{Backend_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Backend_HostAddress}}/auth/authinfo

###

GET {{Backend_HostAddress}}/auth/logout

###

GET {{Backend_HostAddress}}/auth/login/google?returnurl=https://localhost:7004/reqeusts/123425235

###

GET https://localhost:5004/auth/login/google
Content-Type: application/json

{
  "returnurl" : "1234"
}